###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: imobiliaria-redis

    mysql:
      image: mysql:8.0
      container_name: imobiliaria-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=rootpass
        - MYSQL_DATABASE=imobiliaria
        - MYSQL_USER=imobiliaria
        - MYSQL_PASSWORD=1234
      ports:
        - "8092:3306"

    webserver:
      image: nginx:alpine
      container_name: imobiliaria-webserver
      working_dir: /application
      volumes:
          - ./src:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8090:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: imobiliaria-php-fpm
      working_dir: /application
      volumes:
        - ./src:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

